title: Stan Z. Li's Lab
page-top-title: Stan Z. Li's Lab
top-section-bg-text:  AI for Science研究
home-subtitle: 李子青实验室&ensp;|&ensp;Stan Z. Li's Lab
copyright-text: '&copy; Stan Z. Li 2023-2024. All Rights Reserved.'
