title: 李子青实验室
page-top-title: 李子青实验室
top-section-bg-text: AI基础方法 & AI for Science研究
home-subtitle: 李子青实验室&ensp;|&ensp;Stan Z. Li's Lab
copyright-text: '&copy; Stan Z. Li 2023-2024. All Rights Reserved.'
